cask_args appdir: '/Applications'
brew 'ghq'
brew 'peco'
cask 'google-japanese-ime'
cask 'google-chrome'
cask 'google-drive'
cask 'alfred'
cask 'atom'
cask 'evernote'
cask 'bettertouchtool'
cask 'iterm2'
cask 'disk-inventory-x'
cask 'docker'
cask 'cmd-eikana'
