[[plugins]] # カラースキーマ
repo = 'w0ng/vim-hybrid'
hook_add = '''
    colorscheme hybrid
    set background=dark
'''

[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

[[plugins]]
repo = 'kevinw/pyflakes-vim'

[[plugins]]
repo = 'scrooloose/syntastic'
hook_add = '''
    let g:syntastic_python_checkers = ["flake8"]
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  nnoremap T :NERDTreeFocus<CR>
  let NERDTreeShowHidden = 1
  autocmd VimEnter * execute 'NERDTree' 
'''

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
'''
